name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on:
      - macos-11     # macos runner has no Docker
      - ubuntu-20.04 # ubuntu runner has no /dev/kvm

    steps:
    # via https://medium.com/crowdbotics/a-complete-one-by-one-guide-to-install-docker-on-your-mac-os-using-homebrew-e818eb4cfc3
    - name: Install Docker
      run: |-
        brew install docker docker-machine
        docker-machine create --driver virtualbox default
        docker-machine env default
        eval "$(docker-machine env default)"
      if: ${{ env.RUNNER_OS == 'macOS' }}

    - name: Checkout this repo
      uses: actions/checkout@v2

    - name: Fetch Windows XP image
      run: wget -qO en_win_xp_pro_x64_with_sp2_vl_x13-41611.iso ${{ secrets.WINDOWS_XP_ISO_URL }}

    - name: Build Stage 1
      run: |-
        docker build . -f stage1/Dockerfile \
          -t stage1 \
          --build-arg PRODUCT_KEY=${{ secrets.WINDOWS_XP_PRODUCT_KEY }}

    - name: Check for /dev/kvm
      run: |-
        stat /dev/kvm || true

    - name: Execute Stage 1 (with KVM)
      run: |-
        timeout 20m \
          docker run \
            --rm \
            --device /dev/kvm \
            -v $(pwd)/out:/out \
            stage1
      if: ${{ env.RUNNER_OS == 'macOS' }}

    - name: Execute Stage 1 (no KVM)
      run: |-
        timeout 20m \
          docker run \
            --rm \
            --device /dev/kvm \
            -v $(pwd)/out:/out \
            stage1
      if: ${{ env.RUNNER_OS != 'macOS' }}

    - name: Build Stage 2
      run: |-
        docker build . -f stage2/Dockerfile -t xp
